<a href="https://colab.research.google.com/github/Joseberzeker/repositorio/blob/master/Algoritmos_Clasificacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv("datos_desercion.csv", header=0, encoding = 'utf8')

In [ ]:
df.columns

Index(['edad', 'genero', 'estado_civil', 'estrato', 'icfes',
       'titulos_académicos', 'total_materias_perdidas',
       'materias_inscr_ult_período', 'materias_aprob_ult_período',
       'cant_reingresos', 'ult_promedio_acad', 'acceso_splavia', '¿deserta?'],
      dtype='object')

In [ ]:
df['estado_civil'].value_counts()

soltero        82
Soltero        74
soltera         5
Soltera         5
Unión Libre     1
union libre     1
Name: estado_civil, dtype: int64

In [ ]:
df['estado_civil'].replace(to_replace="Soltera",value="soltero", inplace=True)
df['estado_civil'].replace(to_replace="soltera",value="soltero", inplace=True)
df['estado_civil'].replace(to_replace="Soltero",value="soltero", inplace=True)
df['estado_civil'].replace(to_replace="Unión Libre",value="union libre", inplace=True)

In [ ]:
df['estado_civil'].value_counts()

soltero        166
union libre      2
Name: estado_civil, dtype: int64

In [ ]:
df['estado_civil'].isna().sum()

3

In [ ]:
df['genero'].value_counts()

M    157
F     14
Name: genero, dtype: int64

In [ ]:
d = {'M':1, 'F':0}
df['genero'] = df['genero'].map(d)

In [ ]:
df.head(10)

edad  genero estado_civil  estrato  icfes  titulos_académicos  \
0    26       1      soltero        1    230                   0   
1    30       1      soltero        1    439                   0   
2    24       1      soltero        1    237                   0   
3    22       1      soltero        2    236                   1   
4    27       1      soltero        0    452                   0   
5    25       1      soltero        1    516                   0   
6    24       1      soltero        2    293                   0   
7    27       0      soltero        1    962                   0   
8    23       0      soltero        3    239                   0   
9    22       1      soltero        3    270                   0   

   total_materias_perdidas  materias_inscr_ult_período  \
0                        7                           6   
1                        0                           7   
2                        3                           6   
3                        2                           6   
4                        8                           7   
5                        1                           5   
6                        8                           5   
7                        2                           5   
8                        6                           6   
9                        3                           7   

   materias_aprob_ult_período  cant_reingresos  ult_promedio_acad  \
0                           4              1.0               3.10   
1                           7              0.0               3.90   
2                           4              0.0               2.90   
3                           6              0.0               4.10   
4                           2              1.0               1.90   
5                           4              0.0               3.10   
6                           0              1.0               0.46   
7                           3              0.0               3.00   
8                           0              0.0               1.48   
9                           4              0.0               2.90   

   acceso_splavia ¿deserta?  
0               0        no  
1               0        si  
2               0        si  
3               0        no  
4               0        no  
5               0        si  
6               0        si  
7               0        si  
8               0        si  
9               0        si

In [ ]:
d = {'soltero': 0, 'union libre':1}
df['estado_civil'] = df['estado_civil'].map(d)

In [ ]:
df.head(10)

edad  genero  estado_civil  estrato  icfes  titulos_académicos  \
0    26       1           0.0        1    230                   0   
1    30       1           0.0        1    439                   0   
2    24       1           0.0        1    237                   0   
3    22       1           0.0        2    236                   1   
4    27       1           0.0        0    452                   0   
5    25       1           0.0        1    516                   0   
6    24       1           0.0        2    293                   0   
7    27       0           0.0        1    962                   0   
8    23       0           0.0        3    239                   0   
9    22       1           0.0        3    270                   0   

   total_materias_perdidas  materias_inscr_ult_período  \
0                        7                           6   
1                        0                           7   
2                        3                           6   
3                        2                           6   
4                        8                           7   
5                        1                           5   
6                        8                           5   
7                        2                           5   
8                        6                           6   
9                        3                           7   

   materias_aprob_ult_período  cant_reingresos  ult_promedio_acad  \
0                           4              1.0               3.10   
1                           7              0.0               3.90   
2                           4              0.0               2.90   
3                           6              0.0               4.10   
4                           2              1.0               1.90   
5                           4              0.0               3.10   
6                           0              1.0               0.46   
7                           3              0.0               3.00   
8                           0              0.0               1.48   
9                           4              0.0               2.90   

   acceso_splavia ¿deserta?  
0               0        no  
1               0        si  
2               0        si  
3               0        no  
4               0        no  
5               0        si  
6               0        si  
7               0        si  
8               0        si  
9               0        si

In [ ]:
df['estado_civil'].value_counts()

0.0    166
1.0      2
Name: estado_civil, dtype: int64

In [ ]:
d = {'si': 1, 'no':0}
df['¿deserta?'] = df['¿deserta?'].map(d)

In [ ]:
df.head(10)

edad  genero  estado_civil  estrato  icfes  titulos_académicos  \
0    26       1           0.0        1    230                   0   
1    30       1           0.0        1    439                   0   
2    24       1           0.0        1    237                   0   
3    22       1           0.0        2    236                   1   
4    27       1           0.0        0    452                   0   
5    25       1           0.0        1    516                   0   
6    24       1           0.0        2    293                   0   
7    27       0           0.0        1    962                   0   
8    23       0           0.0        3    239                   0   
9    22       1           0.0        3    270                   0   

   total_materias_perdidas  materias_inscr_ult_período  \
0                        7                           6   
1                        0                           7   
2                        3                           6   
3                        2                           6   
4                        8                           7   
5                        1                           5   
6                        8                           5   
7                        2                           5   
8                        6                           6   
9                        3                           7   

   materias_aprob_ult_período  cant_reingresos  ult_promedio_acad  \
0                           4              1.0               3.10   
1                           7              0.0               3.90   
2                           4              0.0               2.90   
3                           6              0.0               4.10   
4                           2              1.0               1.90   
5                           4              0.0               3.10   
6                           0              1.0               0.46   
7                           3              0.0               3.00   
8                           0              0.0               1.48   
9                           4              0.0               2.90   

   acceso_splavia  ¿deserta?  
0               0          0  
1               0          1  
2               0          1  
3               0          0  
4               0          0  
5               0          1  
6               0          1  
7               0          1  
8               0          1  
9               0          1

In [ ]:
df['¿deserta?'].value_counts()

1    125
0     46
Name: ¿deserta?, dtype: int64

In [ ]:
df['¿deserta?'].isna().sum()

0

In [ ]:
df['estado_civil'].isna().sum()

3

In [ ]:
df.fillna(value=df.estado_civil.mean(), inplace=True)

In [ ]:
df.sample(5)

edad  genero  estado_civil  estrato  icfes  titulos_académicos  \
120    37       1      0.011905        2    427                   0   
116    25       1      0.000000        1    270                   0   
166    18       1      0.000000        0      0                   0   
58     24       1      0.000000        1    282                   0   
136    23       1      0.000000        1    286                   0   

     total_materias_perdidas  materias_inscr_ult_período  \
120                        1                           5   
116                        1                           6   
166                        6                           6   
58                         2                           6   
136                        6                           6   

     materias_aprob_ult_período  cant_reingresos  ult_promedio_acad  \
120                           4              0.0                3.9   
116                           6              0.0                4.2   
166                           0              0.0                1.8   
58                            5              2.0                3.7   
136                           0              0.0                0.2   

     acceso_splavia  ¿deserta?  
120               0          1  
116               0          1  
166               0          1  
58                0          0  
136               0          1

In [ ]:
df['estado_civil'].isnull().sum()

0

In [ ]:
y = df.iloc[:,12].values

In [ ]:
x = df.iloc[:,:-1].values

In [ ]:
x[11]

array([ 24. ,   1. ,   0. ,   2. , 735. ,   0. ,   1. ,   5. ,   4. ,
         0. ,   3.1,   0. ])

In [ ]:
from sklearn.model_selection import train_test_split
x_ent, x_pru, y_ent, y_pru = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
#Algoritmo de Arbol de decición
from sklearn.tree import DecisionTreeClassifier
arbol = DecisionTreeClassifier(criterion = 'gini', max_depth = 3)
arbol.fit(x_ent,y_ent)

print("Exactitud del conjunto de entrenamiento de arbol de decicion: {:.2f}".format(arbol.score(x_ent, y_ent)))
print("Exactitud del conjunto de prueba: {:.2f} arbol de decicion".format(arbol.score(x_pru, y_pru)))

Exactitud del conjunto de entrenamiento de arbol de decicion: 0.97
Exactitud del conjunto de prueba: 0.86 arbol de decicion


In [ ]:
#matriz de confusión de arbol de decision
pred = arbol.predict(x_pru)
print(confusion_matrix(y_pru,pred))

[[10  2]
 [ 3 20]]


In [ ]:
#Algoritmo de vecinos k-vecino más cercano
from sklearn.neighbors import KNeighborsClassifier
n_vecinos = 3
knn = KNeighborsClassifier(n_vecinos)
knn.fit(x_ent,y_ent)
print("Exactitud del conjunto de entrenamiento k-nn: {:.2f}".format(knn.score(x_ent, y_ent)))
print("Exactitud del conjunto de prueba k-nn: {:.2f}".format(knn.score(x_pru, y_pru)))

Exactitud del conjunto de entrenamiento k-nn: 0.88
Exactitud del conjunto de prueba k-nn: 0.57


In [ ]:
#matriz de confusión de knn
pred = knn.predict(x_pru)
print(confusion_matrix(y_pru,pred))

[[ 0 12]
 [ 3 20]]


In [ ]:
#reporte
print(classification_report(y_pru, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.62      0.87      0.73        23

    accuracy                           0.57        35
   macro avg       0.31      0.43      0.36        35
weighted avg       0.41      0.57      0.48        35



In [ ]:
#prueba con algoritmo de arbol de decicion
prueba = np.array([30,1,1,2,200,0,10,6,1,5,2.5,0])
prediccion = arbol.predict(prueba.reshape(1,-1))
print("Prediccioón:",prediccion[0])
if(prediccion[0]==1):
  print("Si deserta")
else:
  print("Se gradua")

Prediccioón: 1
Si deserta


In [ ]:
#prueba con algoritmo de k-nn
prueba = np.array([30,1,1,2,200,0,10,6,1,5,2.5,0])
prediccion = knn.predict(prueba.reshape(1,-1))
print("Prediccioón:",prediccion[0])
if(prediccion[0]==1):
  print("Si deserta")
else:
  print("Se gradua")

Prediccioón: 1
Si deserta
